services:
  app:
    container_name: blive-frontend
    image: blive-frontend:v0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    tty: true
